language: python
python:
  - "3.12"

dist: focal

env:
  global:
    - DJANGO_SETTINGS_MODULE=mysite.settings

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test
  - coveralls -v --service=travis-pro

after_success:
  - coveralls